name: CmakeCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt install g++-8 gcc-8 cmake doxygen
    - name: cmake
      working-directory: /home/runner/work/thrp/thrp/
      run: sudo cmake . -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_C_COMPILER=gcc-8
    - name: make
      working-directory: /home/runner/work/thrp/thrp/
      run: sudo make -j4
    - name: test
      working-directory: /home/runner/work/thrp/thrp/
      run: ctest .
